name: 'Test Runner'

# **What it does**: Runs unit tests whenever someone creates a PR.
# **Why we have it**: To give developers feedback if they have broken anything.
# **Who does it impact**: developers and testers.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node modules
        working-directory: ./aws/terraform/nodejs/backend
        run: |
          npm install --save-dev jest
          npm test
